"""
Pydantic schemas for the OpsForge End-to-End Orchestration Pipeline.

Defines the request and response contracts for the unified pipeline that
connects Agent 1 (Planner) → Agent 2 (Deploy) → Agent 3 (RCA) →
Agent 5 (Memory Search) → Agent 4 (Recovery & Voice).
"""

from typing import Any, Dict, List, Optional
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class StageStatus(str, Enum):
    PENDING   = "pending"
    RUNNING   = "running"
    COMPLETED = "completed"
    SKIPPED   = "skipped"
    FAILED    = "failed"


class WorkflowStatus(str, Enum):
    RUNNING             = "running"
    AWAITING_APPROVAL   = "awaiting_approval"
    COMPLETED           = "completed"
    FAILED              = "failed"


# ---------------------------------------------------------------------------
# Request
# ---------------------------------------------------------------------------

class PipelineRequest(BaseModel):
    """
    Top-level request body for POST /pipeline/run.
    Accepted by the OrchestratorService as the pipeline entry point.
    """
    description: str = Field(
        ...,
        description="User deployment intent (e.g. 'Deploy with PostgreSQL and autoscaling')"
    )
    dockerfile: str = Field(
        ...,
        description="Raw Dockerfile content to be parsed by Agent 1"
    )
    simulate_failure: bool = Field(
        default=True,
        description=(
            "When True, the orchestrator injects a controlled failure telemetry payload "
            "into Agent 3 after deployment to trigger a full RCA → Recovery pipeline "
            "cycle. Set to False if the application is expected to remain healthy."
        )
    )


# ---------------------------------------------------------------------------
# Per-Stage Result
# ---------------------------------------------------------------------------

class StageResult(BaseModel):
    """
    Captures the output, timing, and status of a single pipeline stage.
    """
    stage:       str         = Field(..., description="Stage identifier (e.g. PLAN, DEPLOY, RCA, RECOVERY_PLAN)")
    status:      StageStatus = Field(..., description="Stage execution status")
    started_at:  str         = Field(..., description="UTC ISO-8601 timestamp when stage began")
    finished_at: Optional[str] = Field(None, description="UTC ISO-8601 timestamp when stage ended")
    duration_ms: Optional[int] = Field(None, description="Stage wall-clock duration in milliseconds")
    data:        Optional[Dict[str, Any]] = Field(
        default_factory=dict,
        description="Stage output payload (serialized Pydantic model dump)"
    )
    error:       Optional[str] = Field(None, description="Error detail if stage failed")


# ---------------------------------------------------------------------------
# Full Workflow Result
# ---------------------------------------------------------------------------

class WorkflowResult(BaseModel):
    """
    Complete E2E pipeline execution result returned by POST /pipeline/run.

    Contains the structured output from every stage plus a recovery_action_id
    that the frontend uses to drive the operator approval flow via the existing
    /recovery/{id}/approve and /recovery/{id}/execute REST endpoints.
    """
    trace_id:          str             = Field(..., description="Globally unique trace identifier for this pipeline run")
    workflow_status:   WorkflowStatus  = Field(..., description="Overall pipeline execution status")
    stages:            List[StageResult] = Field(default_factory=list, description="Ordered list of stage execution results")

    # Cross-stage summary fields (populated from stage outputs)
    app_name:          Optional[str]   = Field(None, description="Deployed application name")
    deployment_id:     Optional[str]   = Field(None, description="Deployment run identifier from Agent 2")
    app_id:            Optional[str]   = Field(None, description="Cloud platform application identifier")
    live_url:          Optional[str]   = Field(None, description="Live application URL after successful deployment")
    incident_detected: Optional[bool]  = Field(None, description="Whether Agent 3 detected an active incident")
    severity:          Optional[str]   = Field(None, description="Incident severity classification")
    root_cause:        Optional[str]   = Field(None, description="Root cause statement from Agent 3")
    confidence:        Optional[float] = Field(None, description="Agent 3 RCA confidence score (0.0–1.0)")
    recovery_action_id: Optional[str] = Field(
        None,
        description=(
            "RecoveryAction ID generated by Agent 4. "
            "Use POST /recovery/{id}/approve to submit operator decision, "
            "then POST /recovery/{id}/execute to trigger infrastructure recovery."
        )
    )
    similar_incidents_found: Optional[int] = Field(
        None,
        description="Number of similar historical incidents retrieved from Agent 5 Knowledge Memory"
    )

    # Timing
    started_at:    str            = Field(..., description="Pipeline start timestamp (UTC ISO-8601)")
    finished_at:   Optional[str]  = Field(None, description="Pipeline completion timestamp (UTC ISO-8601)")
    total_duration_ms: Optional[int] = Field(None, description="Total pipeline wall-clock duration in milliseconds")

    # Error (top-level, if pipeline halted early)
    error: Optional[str] = Field(None, description="Top-level error detail if pipeline was aborted")
