from typing import Optional, Any
from app.schemas.deployment import DeploymentPlan, DeploymentResult
from app.services.deployment_service import DeploymentService
from app.services.pipeline_bridge_service import PipelineBridgeService
from app.agents.root_cause import RootCauseAgent
from app.utils.logger import get_logger

logger = get_logger()

class InfraDeployAgent:
    """
    Agent 2 (Infra & Deploy Agent).
    Receives abstract DeploymentPlan JSON generated by Agent 1, validates plan compatibility,
    provisions target infrastructure via Railway + GitHub Actions, and returns execution status.
    Automatically transmits deployment metadata to Agent 3 upon active deployment.
    """
    def __init__(
        self,
        deployment_service: Optional[DeploymentService] = None,
        root_cause_agent: Optional[RootCauseAgent] = None
    ):
        self.deployment_service = deployment_service or DeploymentService()
        self.root_cause_agent = root_cause_agent or RootCauseAgent()

    async def deploy(self, plan: DeploymentPlan) -> DeploymentResult:
        """
        Executes Agent 2 deployment pipeline using the provided DeploymentPlan.
        Transmits deployment metadata to Agent 3 upon active deployment.
        """
        logger.info(f"Agent 2 (Infra & Deploy) received plan for application '{plan.application.name}'.")
        result = await self.deployment_service.execute_deployment(plan)

        # After deployment becomes ACTIVE, automatically transform and send metadata to Agent 3
        if result.status == "success":
            logger.info(f"Agent 2: Active deployment '{result.deployment_id}' for app '{result.app_id}'. Sending metadata to Agent 3.")
            incident_request = PipelineBridgeService.transform_deployment_to_incident_request(result)
            try:
                await self.root_cause_agent.run(incident_request)
            except Exception as e:
                logger.warning(f"Agent 2 -> Agent 3 metadata transmission warning: {e}")

        return result

    async def execute_recovery(self, action: Any):
        """
        Agent 2 interface method for executing approved recovery actions (rollback, restart, scale, redeploy).
        Validates request payload and delegates infrastructure execution to DeploymentService.
        """
        logger.info(f"Agent 2 (Infra & Deploy) received recovery action '{action.id}' ({action.title}) for execution.")
        return await self.deployment_service.execute_recovery_action(action)

# Singleton instance for route handler reuse
infra_deploy_agent = InfraDeployAgent()

